name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  shelf: ^1.3.2
  shelf_router: ^1.1.3
  path: ^1.8.0
  dart_jsonwebtoken: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
